name: Auto merge
on:
  pull_request:
permissions:
  contents: write
  checks: read
  pull-requests: write
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@a9fc2fae0eceafcdd4a812c23a3febd9c416428b # pinned to latest
    with:
      azure_cloud: true
      tfchecks_azure: '["tf-lint / tflint"]'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
