name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@58ff87df0f3a8b2cd098ed7e85c0c80c17c28f60 # pinned to latest
    secrets: inherit
